name: ya_stukachok_platform_interface
description: Platform interface for importing web only Yandex.Metrika to cross-platform app.
version: 0.0.1
author: Ilya Yachin

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.1.0-nullsafety.1
  json_annotation: ^4.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter